import Student from "./Student.js";

let student1 = new Student('Misha','Voronin',2000);

student1.present();
student1.setMark(70);
student1.present();
student1.setMark(90);
student1.present();
student1.absent();
student1.setMark(70);
student1.absent();
student1.absent();
student1.absent();
student1.absent();
student1.present();
student1.setMark(80);
student1.present();
student1.setMark(80);
student1.present();
student1.setMark(80);
student1.present();
student1.setMark(80);
student1.present();
student1.setMark(70);
student1.present();
student1.setMark(90);
student1.present();
student1.setMark(80);
student1.absent();
student1.setMark(70);
student1.absent();
student1.absent();
student1.absent();
student1.absent();
student1.present();
student1.setMark(80);
student1.present();
student1.setMark(80);
student1.present();
student1.setMark(80);
student1.present();
student1.setMark(80);
student1.present();
student1.setMark(80);

console.log(`${student1.getFirstName()} ${student1.getLastName()} ${student1.getAge()}` );
console.log(student1.summary());

let student2 = new Student('Liza','Bumer',2005);

student2.present();
student2.setMark(70);
student2.present();
student2.setMark(90);
student2.present();
student2.absent();
student2.present();
student2.setMark(90);
student2.present();
student2.setMark(90);
student2.present();
student2.present();
student2.setMark(90);
student2.present();
student2.setMark(90);
student2.present();
student2.present();
student2.setMark(90);
student2.present();
student2.setMark(90);
student2.present();
student2.present();
student2.setMark(90);
student2.present();
student2.setMark(90);
student2.present();
student2.present();
student2.setMark(90);
student2.present();
student2.setMark(90);
student2.present();
student2.present();
student2.setMark(90);

console.log(`${student2.getFirstName()} ${student2.getLastName()} ${student2.getAge()}` );
console.log(student2.summary());